# Generated by Django 5.0.3 on 2024-03-30 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_profilepayment_delete_userpayment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
    ]
