# Generated by Django 5.0.3 on 2024-03-30 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_donation_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Donation',
        ),
        migrations.AddField(
            model_name='profilepayment',
            name='donation_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='profilepayment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
