# Generated by Django 5.0.3 on 2024-03-30 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_delete_donation_profilepayment_donation_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilepayment',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.profile'),
        ),
    ]
