# Generated by Django 5.0.3 on 2024-03-30 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_profilepayment_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='amount_donated',
        ),
    ]
