# Generated by Django 5.0.3 on 2024-03-30 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_remove_profile_amount_donated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundraiser',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=10),
        ),
    ]
