# Generated by Django 5.0.3 on 2024-04-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_fundraiser_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_donated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
