# Generated by Django 5.0.3 on 2024-04-03 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_profile_total_donated'),
    ]

    operations = [
        migrations.AddField(
            model_name='fundraiser',
            name='goal_amount',
            field=models.DecimalField(decimal_places=2, default=2000.0, max_digits=10),
        ),
    ]
