# Generated by Django 5.0.3 on 2024-04-03 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_profile_total_donated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='total_amount_donated',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
