# Generated by Django 5.0.3 on 2024-04-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_remove_comment_content_alter_fundraiser_goal_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default='your comment'),
        ),
    ]
