# Generated by Django 5.0.3 on 2024-04-04 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_comment_content'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fundraiser',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='total_amount_donated',
        ),
        migrations.AlterField(
            model_name='profilepayment',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime),
        ),
    ]
